### PR TITLE
adding sample templates for Fargate microservices workloads

### PR DESCRIPTION
**Pull request by henrybravo**
*Description of changes:*
This PR implements a new directory `public-private-fargate-microservices` containing a sample AWS Proton Environment and 2 Service templates (Public & Private), a set of Amazon ECS based microservices using service discovery and running on AWS Fargate, as well as sample specs for creating Proton Environments and Services using the templates. All resources deployed are tagged.
Based on the existing `loadbalanced-fargate-svc` this sample deploys:
- a VPC
- an Internet Gateway
- 2 Nat Gateways across 2 Availability Zones
- 2 private subnets across 2 Availability Zones
- 2 public subnets across 2 Availability Zones
- an ECS Cluster
- a private namespace for service discovery

The service templates contains all the resources required to create a public ECS Fargate service behind a load balancer and a private ECS Fargate service in that environment taking the following options for configuration:
- Fargate CPU size
- Fargate memory size
- Number of running containers
- Choose private or public subnets to run the loadbalanced service or the private service, accessed via service discovery
- Service name to register and use for service discovery

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rafavallina** [comment]
Hi @henrybravo just wanted to acknowledge that I've seen this and I'm looking into it, will come back as soon as possible. Thank so much!

**Comment by rafavallina** [comment]
Hi @henrybravo I finally looked at this. This looks good and I'm ready to merge, but I would recommend one update first: if you look at the current Fargate sample template in the repo, we've done away with the field `{{service_instance.unique_name}}`, because now you can use directly `{{service_name}}` and `{{service_instance_name}}`. See here:

- Updated schema without the `unique_name` field: https://github.com/aws-samples/aws-proton-sample-templates/blob/main/loadbalanced-fargate-svc/service/schema/schema.yaml
- Using the `{{service_name}}` and `{{service_instance_name}}` parameters: https://github.com/aws-samples/aws-proton-sample-templates/blob/9cc55b5b15e9ad1fd121b207c909b5098bb2e901/loadbalanced-fargate-svc/service/infrastructure/cloudformation.yaml#L25
- Using the `{{service_name}}` and `{{service_instance_name}}` parameters, with some Jinja parsing to meet requirements for length: https://github.com/aws-samples/aws-proton-sample-templates/blob/9cc55b5b15e9ad1fd121b207c909b5098bb2e901/loadbalanced-fargate-svc/service/infrastructure/cloudformation.yaml#L100

This prevents the developer from having to enter `unique_name` as a parameter and also gives more consistency to how things are name after they are provisioned. Can we make these update before I merge?

Thanks!

**Comment by henrybravo** [comment]
Hi @rafavallina, I've updated the service templates now by omitting the unique_name is the service specs

**Comment by rafavallina** [comment]
Merged! Thanks for your contribution :)

**Pull request merged**
